name: rina-deploy

on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build project
      run: cargo build --release

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "target/release/rina"
        target: "~/rina"

    - name: Execute remote command
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo systemctl restart rina
